package com.example.weatherproject.util

const val HOME_DEFAULT_CITY = "Los Angeles"
const val MEXICO_CITY_LIST_NAME = "Mexico City"
const val TORONTO_LIST_NAME = "Toronto"
const val VANCOUVER_LIST_NAME = "Vancouver"
const val SAN_FRANCISCO_LIST_NAME = "San Francisco"
const val PARIS_LIST_NAME = "Paris"
const val MERIDA_LIST_NAME = "Merida"
const val ROMA_LIST_NAME = "Roma"
const val MEDELLIN_CITY_LIST_NAME = "Medellin"
const val RIO_DE_JANEIRO_LIST_NAME = "Rio de Janeiro"
const val ALASKA_LIST_NAME = "Alaska"
const val TEMPERATURE_UNIT = "°F"
const val PERCENT_SIGN = "%"
const val SELECT_A_CITY_LABEL = "Select a city:"
const val DESCRIPTION_LABEL = "Description"
const val HUMIDITY_LABEL = "Humidity"
const val COUNTRY_LABEL = "Country"
const val WEATHER_LABEL = "Weather"
const val DEFAULT_STATE_LABEL = "Select a city to get the weather."
const val DROPDOWN_ICON_LABEL = "Dropdown Icon"
